In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame({
    "value": [1000, 2000],
    "quantity": [10, 20]
})

df.head()

   value  quantity
0   1000        10
1   2000        20

In [4]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   value     2 non-null      int64
 1   quantity  2 non-null      int64
dtypes: int64(2)
memory usage: 164.0 bytes

             value   quantity
count     2.000000   2.000000
mean   1500.000000  15.000000
std     707.106781   7.071068
min    1000.000000  10.000000
25%    1250.000000  12.500000
50%    1500.000000  15.000000
75%    1750.000000  17.500000
max    2000.000000  20.000000